version: '3'

services:
  memos-wechat-proxy:
    build: .
    container_name: memos-wechat-proxy
    ports:
      - 5000:5000
    volumes:
      - ./config.ini:/app/config.ini
    stop_signal: SIGINT